version: "3.3"
services:

  db:
    image: postgres:12.1-alpine
    volumes:
      - pgdata_volume:/var/lib/postgresql/data/
    ports:
      - 5437:5432
    environment:
      - POSTGRES_DB=karaoke
      - POSTGRES_USER=karaoke
      - POSTGRES_PASSWORD=karaokepass
  redis:
    restart: always
    image: redis:latest
    ports:
      - 6385:6379
volumes:
  pgdata_volume:


# celery -A tb_karaoke worker --loglevel=info
# celery -A tb_karaoke beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler