# Generated by Django 3.2.25 on 2024-04-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tester',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tester',
            name='username',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
