# Generated by Django 3.2.25 on 2024-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_day_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiles',
            name='block',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
