# Generated by Django 3.2.25 on 2024-04-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_audiofiles_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='block',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
