# Generated by Django 3.2.25 on 2024-04-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240429_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationquestion',
            options={'ordering': ['created'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='applicationquestion',
            name='n',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
