# Generated by Django 3.2.25 on 2024-04-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240430_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='last_question',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
