# Generated by Django 3.2.25 on 2024-05-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='chat_id',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
