# Generated by Django 3.2.25 on 2024-05-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tester_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiles',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
