# Generated by Django 3.2.25 on 2024-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_audiofiles_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='current_block',
            field=models.IntegerField(default=1),
        ),
    ]
