# Generated by Django 3.2.25 on 2024-05-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tester_current_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='day',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
