# Generated by Django 3.2.25 on 2024-06-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240526_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='audio_message_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
