# Generated by Django 3.2.25 on 2024-06-10 18:17

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mark_audio_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('success_resend', models.BooleanField(default=False)),
                ('audio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='error_logs', to='core.audiofiles')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='error_logs', to='core.tester')),
            ],
            options={
                'verbose_name': 'Лог ошибки',
                'verbose_name_plural': 'Логи ошибки',
                'ordering': ['-created'],
            },
        ),
    ]
