# Generated by Django 3.2.25 on 2024-06-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='second_description',
            field=models.TextField(null=True),
        ),
    ]
