# Generated by Django 3.2.25 on 2024-07-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_errorlog_second_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('tester', 'audio')},
        ),
    ]
